# Generated by Django 6.0.7 on 2026-07-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision_ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visionanalysis',
            new_name='vision_ai_v_organiz_a9c687_idx',
            old_name='vision_ai_v_organiz_3cc2af_idx',
        ),
        migrations.RenameIndex(
            model_name='visionanalysis',
            new_name='vision_ai_v_scene_i_b48a0c_idx',
            old_name='vision_ai_v_scene_i_1d6014_idx',
        ),
        migrations.RenameIndex(
            model_name='visiondetection',
            new_name='vision_ai_v_analysi_69d6bc_idx',
            old_name='vision_ai_v_analysi_5b6194_idx',
        ),
    ]
