from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0003_organization_logo"),
        ("tours", "0010_hotspot_door_and_advanced_display"),
        ("vendors", "0006_alter_deliveryzone_options_and_more"),
    ]
    operations = [
        migrations.CreateModel(name="ProductVisualProfile", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("image_hash",models.CharField(blank=True,db_index=True,max_length=64)),("detected_labels",models.JSONField(blank=True,default=list)),("visual_embedding",models.JSONField(blank=True,default=list)),("primary_category",models.CharField(blank=True,max_length=120)),("dominant_features",models.JSONField(blank=True,default=list)),("indexed_at",models.DateTimeField(blank=True,null=True)),("product",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="tour_ai_visual_profile",to="vendors.product"))]),
        migrations.CreateModel(name="TourSceneAIProfile", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("image_hash",models.CharField(blank=True,db_index=True,max_length=64)),("local_scene_type",models.CharField(blank=True,max_length=120)),("local_scene_confidence",models.FloatField(default=0)),("local_detections",models.JSONField(blank=True,default=list)),("local_features",models.JSONField(blank=True,default=list)),("gemini_summary",models.TextField(blank=True)),("gemini_payload",models.JSONField(blank=True,default=dict)),("final_scene_type",models.CharField(blank=True,max_length=120)),("final_summary",models.TextField(blank=True)),("final_features",models.JSONField(blank=True,default=list)),("commercial_intents",models.JSONField(blank=True,default=list)),("suggested_questions",models.JSONField(blank=True,default=list)),("suggested_opening_message",models.CharField(blank=True,max_length=500)),("analysis_source",models.CharField(choices=[("local","Local"),("hybrid","Hybrid"),("gemini","Gemini")],default="local",max_length=20)),("analysis_confidence",models.FloatField(default=0)),("analysis_version",models.PositiveIntegerField(default=1)),("analyzed_at",models.DateTimeField(blank=True,null=True)),("last_error",models.TextField(blank=True)),("scene",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="tour_ai_profile",to="tours.scene360"))]),
        migrations.CreateModel(name="TourAgentConversation", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("visitor_id",models.CharField(db_index=True,max_length=120)),("session_id",models.CharField(db_index=True,max_length=120)),("status",models.CharField(choices=[("active","Active"),("converted","Converted"),("closed","Closed")],default="active",max_length=20)),("locale",models.CharField(default="en",max_length=16)),("detected_intent",models.CharField(blank=True,max_length=100)),("lead_score",models.PositiveSmallIntegerField(default=0)),("summary",models.TextField(blank=True)),("consent_marketing",models.BooleanField(default=False)),("last_activity_at",models.DateTimeField(auto_now=True)),("organization",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="tour_ai_conversations",to="organizations.organization")),("scene",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="ai_conversations",to="tours.scene360")),("tour",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="ai_conversations",to="tours.tour")),("user",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="tour_ai_conversations",to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="SceneAIRegion", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("label",models.CharField(max_length=120)),("yaw_min",models.FloatField()),("yaw_max",models.FloatField()),("pitch_min",models.FloatField()),("pitch_max",models.FloatField()),("confidence",models.FloatField(default=0)),("product",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="tour_ai_regions",to="vendors.product")),("scene",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="tour_ai_regions",to="tours.scene360"))]),
        migrations.CreateModel(name="SceneProductMatch", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("confidence",models.FloatField(default=0)),("match_reason",models.TextField(blank=True)),("is_verified",models.BooleanField(default=False)),("product",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="tour_ai_scene_matches",to="vendors.product")),("scene",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="tour_ai_product_matches",to="tours.scene360"))], options={"constraints":[models.UniqueConstraint(fields=("scene","product"),name="tour_ai_unique_scene_product")]}),
        migrations.CreateModel(name="VisitorSignal", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("signal_type",models.CharField(db_index=True,max_length=80)),("payload",models.JSONField(blank=True,default=dict)),("conversation",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="signals",to="tour_ai_agent.touragentconversation")),("scene",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="tours.scene360"))]),
        migrations.CreateModel(name="TourAgentMessage", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("role",models.CharField(choices=[("user","User"),("assistant","Assistant"),("tool","Tool"),("system","System")],max_length=20)),("content",models.TextField(blank=True)),("metadata",models.JSONField(blank=True,default=dict)),("conversation",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="messages",to="tour_ai_agent.touragentconversation"))]),
        migrations.CreateModel(name="TourAgentAction", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("action_type",models.CharField(db_index=True,max_length=80)),("payload",models.JSONField(blank=True,default=dict)),("result",models.JSONField(blank=True,default=dict)),("succeeded",models.BooleanField(default=False)),("conversation",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="actions",to="tour_ai_agent.touragentconversation"))]),
    ]
