# Generated by Django 6.0.7 on 2026-07-21 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('organizations', '0003_organization_logo'),
        ('vendors', '0006_alter_deliveryzone_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280)),
                ('purpose', models.CharField(choices=[('booking', 'Booking'), ('lead', 'Lead'), ('contact', 'Contact'), ('quote', 'Quote request'), ('rsvp', 'RSVP'), ('custom', 'Custom')], default='contact', max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('success_message', models.TextField(default='Thank you. Your request has been received.')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_forms', to='organizations.organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DynamicFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('email', 'Email'), ('phone', 'Phone'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date and time'), ('select', 'Select'), ('multiselect', 'Multiple select'), ('checkbox', 'Checkbox'), ('file', 'File')], default='text', max_length=24)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('options', models.JSONField(blank=True, default=list)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='integrations.dynamicform')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('spam', 'Spam'), ('failed', 'Failed')], db_index=True, default='received', max_length=24)),
                ('data', models.JSONField(default=dict)),
                ('source_url', models.URLField(blank=True)),
                ('visitor_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('related_object_type', models.CharField(blank=True, max_length=120)),
                ('related_object_id', models.CharField(blank=True, max_length=120)),
                ('processing_log', models.JSONField(blank=True, default=list)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='integrations.dynamicform')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('google_calendar', 'Google Calendar'), ('outlook', 'Microsoft Outlook'), ('calendly', 'Calendly'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('smtp', 'Email / SMTP'), ('webhook', 'Webhook')], max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('error', 'Error'), ('disabled', 'Disabled')], db_index=True, default='pending', max_length=24)),
                ('credentials_encrypted', models.TextField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('external_account_id', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_connections', to='organizations.organization')),
            ],
            options={
                'ordering': ('provider', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CalendarResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='Africa/Johannesburg', max_length=80)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_writable', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='integrations.integrationconnection')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_event_id', models.CharField(db_index=True, max_length=255)),
                ('html_link', models.URLField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('timezone', models.CharField(default='Africa/Johannesburg', max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_links', to='vendors.appointmentrequest')),
                ('booking_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_links', to='bookings.bookingrequest')),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_links', to='integrations.calendarresource')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='integrations.integrationconnection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='dynamicform',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_dynamic_form_slug'),
        ),
        migrations.AddConstraint(
            model_name='dynamicformfield',
            constraint=models.UniqueConstraint(fields=('form', 'key'), name='unique_dynamic_form_field_key'),
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.UniqueConstraint(fields=('organization', 'provider', 'name'), name='unique_integration_connection'),
        ),
        migrations.AddConstraint(
            model_name='calendarresource',
            constraint=models.UniqueConstraint(fields=('connection', 'external_id'), name='unique_calendar_resource'),
        ),
    ]
