# Generated by Django 6.0.7 on 2026-07-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='airun',
            new_name='ai_core_air_organiz_9dd2d1_idx',
            old_name='ai_core_air_organiz_915dc7_idx',
        ),
        migrations.RenameIndex(
            model_name='airun',
            new_name='ai_core_air_provide_a916c9_idx',
            old_name='ai_core_air_provide_94336a_idx',
        ),
    ]
