# Generated by Django 6.0.3 on 2026-04-03 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='tours/thumbnails/')),
                ('video_tour', models.FileField(blank=True, null=True, upload_to='tours/videos/')),
                ('virtual_tour_url', models.URLField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('tour_date', models.DateField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('guide_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('radius', models.FloatField(default=100)),
                ('chambres', models.IntegerField(blank=True, null=True)),
                ('balcon', models.BooleanField(default=False)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('parking', models.BooleanField(default=False)),
                ('ascenseur', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='organizations.organization')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='places.place')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scene360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('image_360', models.ImageField(upload_to='tours/panoramas/')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='tours/panoramas/thumbs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('yaw_default', models.FloatField(default=0)),
                ('pitch_default', models.FloatField(default=0)),
                ('hfov_default', models.FloatField(default=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='organizations.organization')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='tours.tour')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TourPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='tours/photos/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_photos', to='organizations.organization')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tours.tour')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotspot_id', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('navigate', 'Navigate'), ('info', 'Info'), ('cta', 'CTA'), ('product', 'Product'), ('custom', 'Custom')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('yaw', models.FloatField()),
                ('pitch', models.FloatField()),
                ('tooltip_text', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('selected_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('ad_image', models.ImageField(blank=True, null=True, upload_to='tours/hotspots/ads/')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='organizations.organization')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='tours.scene360')),
                ('target_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_hotspots', to='tours.scene360')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'scene'], name='tours_hotsp_organiz_5344c6_idx'), models.Index(fields=['scene', 'type'], name='tours_hotsp_scene_i_ff9898_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['organization', 'status'], name='tours_tour_organiz_6aa1da_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['place', 'status'], name='tours_tour_place_i_8f2b04_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['slug'], name='tours_tour_slug_a32940_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['is_featured'], name='tours_tour_is_feat_bdd21d_idx'),
        ),
        migrations.AddIndex(
            model_name='scene360',
            index=models.Index(fields=['organization', 'tour'], name='tours_scene_organiz_2a8bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='scene360',
            index=models.Index(fields=['tour', 'order'], name='tours_scene_tour_id_bca450_idx'),
        ),
    ]
