# Generated by Django 6.0.3 on 2026-04-16 05:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        ('places', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['organization', 'created_at'], name='tours_tour_organiz_678206_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['organization', 'is_featured'], name='tours_tour_organiz_a3f82e_idx'),
        ),
    ]
