# Generated by Django 5.2.13 on 2026-04-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_price_alter_tour_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene360',
            name='image_360_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='tours/panoramas/mobile/'),
        ),
    ]
