# Generated by Django 5.2.13 on 2026-04-17 14:14

import apps.tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_scene360_image_360_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='ad_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tours.models.hotspot_ad_upload_to),
        ),
        migrations.AlterField(
            model_name='scene360',
            name='image_360',
            field=models.ImageField(upload_to=apps.tours.models.scene_panorama_upload_to),
        ),
        migrations.AlterField(
            model_name='scene360',
            name='image_360_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tours.models.scene_panorama_mobile_upload_to),
        ),
        migrations.AlterField(
            model_name='scene360',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tours.models.scene_thumbnail_upload_to),
        ),
        migrations.AlterField(
            model_name='tour',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tours.models.tour_thumbnail_upload_to),
        ),
        migrations.AlterField(
            model_name='tour',
            name='video_tour',
            field=models.FileField(blank=True, null=True, upload_to=apps.tours.models.tour_video_upload_to),
        ),
        migrations.AlterField(
            model_name='tourphoto',
            name='image',
            field=models.ImageField(upload_to=apps.tours.models.tour_photo_upload_to),
        ),
    ]
