# Generated by Django 5.2.13 on 2026-04-19 15:37

import apps.tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_logo'),
        ('tours', '0004_alter_hotspot_ad_image_alter_scene360_image_360_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourphoto',
            name='organization',
        ),
        migrations.AddField(
            model_name='scene360',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('inactive', 'Inactive')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='tour',
            name='thumbnail_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tours.models.tour_thumbnail_mobile_upload_to),
        ),
        migrations.AddIndex(
            model_name='scene360',
            index=models.Index(fields=['tour', 'status'], name='tours_scene_tour_id_7fa690_idx'),
        ),
        migrations.AddIndex(
            model_name='scene360',
            index=models.Index(fields=['organization', 'status'], name='tours_scene_organiz_110c26_idx'),
        ),
        migrations.AddIndex(
            model_name='tourphoto',
            index=models.Index(fields=['tour', 'order'], name='tours_tourp_tour_id_85ad89_idx'),
        ),
    ]
