# Generated by Django 6.0.3 on 2026-05-27 13:22

import apps.tours.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_logo'),
        ('tours', '0005_remove_tourphoto_organization_scene360_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene360Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveIntegerField()),
                ('cube_size', models.PositiveIntegerField(default=512)),
                ('face', models.CharField(choices=[('f', 'Front'), ('b', 'Back'), ('l', 'Left'), ('r', 'Right'), ('u', 'Up'), ('d', 'Down')], max_length=1)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField(default=512)),
                ('height', models.PositiveIntegerField(default=512)),
                ('image', models.ImageField(upload_to=apps.tours.models.scene_tile_upload_to)),
                ('size_kb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quality', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['scene', 'level', 'face', 'y', 'x'],
            },
        ),
        migrations.CreateModel(
            name='TourEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('provider_response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hotspot',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scene360',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scene360',
            name='ai_analysis_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scene360',
            name='ai_analysis_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='scene360',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scene360',
            name='ai_hotspot_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scene360',
            name='ai_hotspot_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scene360',
            name='ai_hotspots_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scene360',
            name='ai_hotspots_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='scene360',
            name='assets_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scene360',
            name='assets_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scene360',
            name='assets_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='scene360',
            name='image_360_original',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tours.models.scene_panorama_original_upload_to),
        ),
        migrations.AddField(
            model_name='scene360',
            name='image_360_preview',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tours.models.scene_panorama_preview_upload_to),
        ),
        migrations.AddField(
            model_name='scene360',
            name='max_tile_cube_size',
            field=models.PositiveIntegerField(default=2048),
        ),
        migrations.AddField(
            model_name='scene360',
            name='prefetch_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scene360',
            name='prefetch_manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scene360',
            name='tile_size',
            field=models.PositiveIntegerField(default=512),
        ),
        migrations.AddField(
            model_name='scene360',
            name='tiles_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scene360',
            name='tiles_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scene360',
            name='tiles_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scene360',
            name='tiles_manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scene360',
            name='tiles_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='tour',
            name='publish_email_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='publish_email_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='thumbnail_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tour',
            name='thumbnail_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='thumbnail_source',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tours.models.tour_thumbnail_source_upload_to),
        ),
        migrations.AddField(
            model_name='tour',
            name='thumbnail_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='scene360',
            name='image_360',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tours.models.scene_panorama_upload_to),
        ),
        migrations.AddIndex(
            model_name='hotspot',
            index=models.Index(fields=['scene', 'is_ai_generated'], name='tours_hotsp_scene_i_f50a75_idx'),
        ),
        migrations.AddIndex(
            model_name='scene360',
            index=models.Index(fields=['assets_status'], name='tours_scene_assets__9db713_idx'),
        ),
        migrations.AddIndex(
            model_name='scene360',
            index=models.Index(fields=['tiles_status'], name='tours_scene_tiles_s_0b6da3_idx'),
        ),
        migrations.AddIndex(
            model_name='scene360',
            index=models.Index(fields=['ai_analysis_status'], name='tours_scene_ai_anal_d78a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='scene360',
            index=models.Index(fields=['ai_hotspots_status'], name='tours_scene_ai_hots_30553c_idx'),
        ),
        migrations.AddField(
            model_name='scene360tile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_360_tiles', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='scene360tile',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='tours.scene360'),
        ),
        migrations.AddField(
            model_name='touremaillog',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='tours.tour'),
        ),
        migrations.AddIndex(
            model_name='scene360tile',
            index=models.Index(fields=['organization', 'scene'], name='tours_scene_organiz_054b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='scene360tile',
            index=models.Index(fields=['scene', 'level'], name='tours_scene_scene_i_7e95c2_idx'),
        ),
        migrations.AddIndex(
            model_name='scene360tile',
            index=models.Index(fields=['scene', 'level', 'face'], name='tours_scene_scene_i_acb89d_idx'),
        ),
        migrations.AddIndex(
            model_name='scene360tile',
            index=models.Index(fields=['scene', 'face', 'x', 'y'], name='tours_scene_scene_i_6d1e34_idx'),
        ),
        migrations.AddConstraint(
            model_name='scene360tile',
            constraint=models.UniqueConstraint(fields=('scene', 'level', 'face', 'x', 'y'), name='unique_scene360_tile'),
        ),
        migrations.AddIndex(
            model_name='touremaillog',
            index=models.Index(fields=['tour', 'status'], name='tours_toure_tour_id_32dd3e_idx'),
        ),
        migrations.AddIndex(
            model_name='touremaillog',
            index=models.Index(fields=['recipient'], name='tours_toure_recipie_75cf8c_idx'),
        ),
    ]
