# Generated by Django 6.0.3 on 2026-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_logo'),
        ('tours', '0006_scene360tile_touremaillog_hotspot_is_ai_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene360',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='scene360',
            index=models.Index(fields=['tour', 'is_public'], name='tours_scene_tour_id_17fd34_idx'),
        ),
        migrations.AddIndex(
            model_name='scene360',
            index=models.Index(fields=['organization', 'is_public'], name='tours_scene_organiz_0ac1b6_idx'),
        ),
        migrations.AddIndex(
            model_name='scene360',
            index=models.Index(fields=['tour', 'is_public', 'order'], name='tours_scene_tour_id_a70638_idx'),
        ),
    ]
