# Generated by Django 6.0.3 on 2026-06-04 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_scene360_is_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_key', models.CharField(db_index=True, max_length=120)),
                ('channel', models.CharField(choices=[('web_share', 'Web Share'), ('copy_link', 'Copy Link'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('other', 'Other')], default='other', max_length=30)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, default='', max_length=64)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tours.tour')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tour', 'created_at'], name='tours_tours_tour_id_53e9fe_idx'), models.Index(fields=['tour', 'channel'], name='tours_tours_tour_id_01875c_idx'), models.Index(fields=['visitor_key'], name='tours_tours_visitor_aba753_idx')],
            },
        ),
        migrations.CreateModel(
            name='TourUniqueView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_key', models.CharField(db_index=True, max_length=120)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, default='', max_length=64)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_views', to='tours.tour')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_unique_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tour', 'visitor_key'], name='tours_touru_tour_id_f8502c_idx'), models.Index(fields=['tour', 'created_at'], name='tours_touru_tour_id_60e6ca_idx')],
                'constraints': [models.UniqueConstraint(fields=('tour', 'visitor_key'), name='unique_tour_view_per_visitor')],
            },
        ),
    ]
