import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import apps.tours.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tours", "0011_repair_legacy_ai_analysis_statuses"),
        ("vision_ai", "0003_ocr_metadata_vision_insight"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourArchitectureRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("review", "Ready for review"), ("applied", "Applied"), ("failed", "Failed")], db_index=True, default="queued", max_length=20)),
                ("stage", models.CharField(blank=True, default="queued", max_length=80)),
                ("provider", models.CharField(blank=True, default="gemini", max_length=32)),
                ("model_name", models.CharField(blank=True, default="", max_length=120)),
                ("scene_count", models.PositiveIntegerField(default=0)),
                ("object_count", models.PositiveIntegerField(default=0)),
                ("proposal_count", models.PositiveIntegerField(default=0)),
                ("applied_count", models.PositiveIntegerField(default=0)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=120)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tour_architecture_runs", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tour_architecture_runs", to="organizations.organization")),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="architecture_runs", to="tours.tour")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="SceneVisualQuality",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("ready", "Ready"), ("failed", "Failed")], db_index=True, default="pending", max_length=20)),
                ("overall_score", models.FloatField(default=0)),
                ("sharpness_score", models.FloatField(default=0)),
                ("exposure_score", models.FloatField(default=0)),
                ("contrast_score", models.FloatField(default=0)),
                ("resolution_score", models.FloatField(default=0)),
                ("seam_score", models.FloatField(default=0)),
                ("horizon_score", models.FloatField(default=0)),
                ("source_width", models.PositiveIntegerField(default=0)),
                ("source_height", models.PositiveIntegerField(default=0)),
                ("requires_reupload", models.BooleanField(default=False)),
                ("enhanced_preview", models.ImageField(blank=True, null=True, upload_to=apps.tours.models.tour_intelligence_upload_to)),
                ("issues", models.JSONField(blank=True, default=list)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, default="", max_length=80)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                ("analysis", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="scene_quality_assessments", to="vision_ai.visionanalysis")),
                ("scene", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="visual_quality", to="tours.scene360")),
            ],
            options={"ordering": ("scene__order", "scene_id")},
        ),
        migrations.CreateModel(
            name="SceneObjectCandidate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("kind", models.CharField(choices=[("object", "Object"), ("text", "Text"), ("portal", "Navigation anchor")], db_index=True, default="object", max_length=20)),
                ("label", models.CharField(db_index=True, max_length=180)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("confidence", models.FloatField(default=0)),
                ("bbox", models.JSONField(blank=True, default=list)),
                ("yaw", models.FloatField(default=0, help_text="Panorama yaw in radians.")),
                ("pitch", models.FloatField(default=0, help_text="Panorama pitch in radians.")),
                ("crop_image", models.ImageField(blank=True, null=True, upload_to=apps.tours.models.tour_intelligence_upload_to)),
                ("enhanced_crop_image", models.ImageField(blank=True, null=True, upload_to=apps.tours.models.tour_intelligence_upload_to)),
                ("clarity_score", models.FloatField(default=0)),
                ("quality_score", models.FloatField(default=0)),
                ("is_navigation_anchor", models.BooleanField(db_index=True, default=False)),
                ("client_ready", models.BooleanField(db_index=True, default=False)),
                ("review_status", models.CharField(choices=[("suggested", "Suggested"), ("approved", "Approved"), ("rejected", "Rejected"), ("hidden", "Hidden")], db_index=True, default="suggested", max_length=20)),
                ("issues", models.JSONField(blank=True, default=list)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("source_providers", models.JSONField(blank=True, default=list)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("analysis", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tour_object_candidates", to="vision_ai.visionanalysis")),
                ("detection", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tour_object_candidates", to="vision_ai.visiondetection")),
                ("frame", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tour_object_candidates", to="vision_ai.visionframe")),
                ("scene", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="object_candidates", to="tours.scene360")),
            ],
            options={"ordering": ("scene__order", "-confidence", "id")},
        ),
        migrations.CreateModel(
            name="SceneLinkProposal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_yaw", models.FloatField(default=0)),
                ("from_pitch", models.FloatField(default=0)),
                ("to_yaw", models.FloatField(default=0)),
                ("to_pitch", models.FloatField(default=0)),
                ("confidence", models.FloatField(default=0)),
                ("rationale", models.TextField(blank=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(choices=[("gemini", "Gemini"), ("deterministic", "Deterministic fallback"), ("manual", "Manual")], default="gemini", max_length=24)),
                ("status", models.CharField(choices=[("suggested", "Suggested"), ("approved", "Approved"), ("rejected", "Rejected"), ("applied", "Applied"), ("conflict", "Conflict")], db_index=True, default="suggested", max_length=20)),
                ("is_bidirectional", models.BooleanField(default=True)),
                ("manual_adjusted", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("applied_from_hotspot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="architect_primary_proposals", to="tours.hotspot")),
                ("applied_reverse_hotspot", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="architect_reverse_proposals", to="tours.hotspot")),
                ("from_anchor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="outgoing_link_proposals", to="tours.sceneobjectcandidate")),
                ("from_scene", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outgoing_link_proposals", to="tours.scene360")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_scene_link_proposals", to=settings.AUTH_USER_MODEL)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="proposals", to="tours.tourarchitecturerun")),
                ("to_anchor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="incoming_link_proposals", to="tours.sceneobjectcandidate")),
                ("to_scene", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="incoming_link_proposals", to="tours.scene360")),
                ("tour", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scene_link_proposals", to="tours.tour")),
            ],
            options={"ordering": ("from_scene__order", "-confidence", "id")},
        ),
        migrations.AddConstraint(
            model_name="sceneobjectcandidate",
            constraint=models.UniqueConstraint(fields=("analysis", "fingerprint"), name="unique_scene_object_candidate"),
        ),
        migrations.AddConstraint(
            model_name="scenelinkproposal",
            constraint=models.UniqueConstraint(fields=("run", "from_scene", "to_scene"), name="unique_architect_link_per_run"),
        ),
        migrations.AddIndex(model_name="tourarchitecturerun", index=models.Index(fields=["tour", "status", "created_at"], name="tours_tour_tour_id_41b7cf_idx")),
        migrations.AddIndex(model_name="tourarchitecturerun", index=models.Index(fields=["organization", "status", "created_at"], name="tours_tour_organiz_eb723d_idx")),
        migrations.AddIndex(model_name="scenevisualquality", index=models.Index(fields=["status", "overall_score"], name="tours_scene_status_608a1b_idx")),
        migrations.AddIndex(model_name="scenevisualquality", index=models.Index(fields=["requires_reupload", "overall_score"], name="tours_scene_require_6fe367_idx")),
        migrations.AddIndex(model_name="sceneobjectcandidate", index=models.Index(fields=["scene", "review_status", "client_ready"], name="tours_scene_scene_i_403c49_idx")),
        migrations.AddIndex(model_name="sceneobjectcandidate", index=models.Index(fields=["scene", "is_navigation_anchor", "confidence"], name="tours_scene_scene_i_9bff47_idx")),
        migrations.AddIndex(model_name="sceneobjectcandidate", index=models.Index(fields=["kind", "confidence"], name="tours_scene_kind_f1259c_idx")),
        migrations.AddIndex(model_name="scenelinkproposal", index=models.Index(fields=["tour", "status", "confidence"], name="tours_scene_tour_id_0b520b_idx")),
        migrations.AddIndex(model_name="scenelinkproposal", index=models.Index(fields=["from_scene", "to_scene", "status"], name="tours_scene_from_sc_35768f_idx")),
    ]
