# Generated by Django 6.0.3 on 2026-04-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceMapContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('street_view_available', models.BooleanField(default=False)),
                ('street_view_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('street_view_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('pitch', models.FloatField(blank=True, null=True)),
                ('zoom', models.FloatField(blank=True, null=True)),
                ('geocode_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
