# Generated by Django 6.0.7 on 2026-07-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_enable_pgvector'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knowledgechunk',
            new_name='knowledge_k_documen_af5271_idx',
            old_name='knowledge_k_documen_e8de0a_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgedocument',
            new_name='knowledge_k_source__42a4a1_idx',
            old_name='knowledge_k_source__f52921_idx',
        ),
    ]
