# Generated by Django 6.0.3 on 2026-04-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('service_interest', models.CharField(choices=[('virtual_tour', '360° Virtual Tour'), ('hotspots', 'Interactive Hotspots'), ('showcase', 'Property / Venue Showcase'), ('lead_capture', 'Lead Capture & Booking'), ('branding', 'Branded Presentation'), ('other', 'Other')], default='virtual_tour', max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Lead',
                'verbose_name_plural': 'Contact Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
