# Generated by Django 6.0.7 on 2026-07-21 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_agents', '0001_initial'),
        ('organizations', '0003_organization_logo'),
        ('tours', '0010_hotspot_door_and_advanced_display'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('locale', models.CharField(default='en', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='active', max_length=24)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('lead_score', models.PositiveSmallIntegerField(default=0)),
                ('consent_marketing', models.BooleanField(default=False)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='ai_agents.agentdefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_conversations', to='organizations.organization')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_conversations', to='tours.scene360')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_conversations', to='tours.tour')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_activity_at',),
            },
        ),
        migrations.CreateModel(
            name='EnterpriseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=16)),
                ('content', models.TextField(blank=True)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0)),
                ('intent', models.CharField(blank=True, max_length=120)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_chat.enterpriseconversation')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ConversationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('helpful', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_chat.enterpriseconversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='ai_chat.enterprisemessage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='enterpriseconversation',
            index=models.Index(fields=['organization', 'status', 'last_activity_at'], name='ai_chat_ent_organiz_f9fd9e_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisemessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_chat_ent_convers_36c292_idx'),
        ),
    ]
