# Generated by ChatGPT for the advanced Street View Studio layer.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0001_initial'),
        ('app_streetview', '0002_streetviewsourcepublication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetViewQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('needs_attention', 'Needs attention'), ('blocked', 'Blocked')], default='needs_attention', max_length=32)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('blockers', models.PositiveIntegerField(default=0)),
                ('warnings', models.PositiveIntegerField(default=0)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reports', to='app_streetview.streetviewsourcepublication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streetview_quality_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreetViewHistoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('quality_check', 'Quality check'), ('smart_link', 'Smart link'), ('auto_link', 'Auto link'), ('manual_link', 'Manual link'), ('scene_update', 'Scene update'), ('publish_started', 'Publish started'), ('publish_finished', 'Publish finished'), ('publish_failed', 'Publish failed'), ('connections_retried', 'Connections retried'), ('google_photo_deleted', 'Google photo deleted'), ('google_photo_linked', 'Google photo linked'), ('other', 'Other')], default='other', max_length=48)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_events', to='app_streetview.streetviewsourcepublishjob')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='app_streetview.streetviewsourcepublication')),
                ('source_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streetview_history_events', to='tours.scene360')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streetview_history_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreetViewAnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tour_opened', 'Tour opened'), ('scene_selected', 'Scene selected'), ('camera_saved', 'Camera saved'), ('quality_check', 'Quality check'), ('smart_link_applied', 'Smart link applied'), ('publish_started', 'Publish started'), ('publish_succeeded', 'Publish succeeded'), ('publish_failed', 'Publish failed'), ('google_library_opened', 'Google library opened'), ('google_photo_opened', 'Google photo opened'), ('other', 'Other')], default='other', max_length=48)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='app_streetview.streetviewsourcepublication')),
                ('source_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streetview_analytics_events', to='tours.scene360')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streetview_analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='streetviewqualityreport',
            index=models.Index(fields=['publication', 'created_at'], name='sv_quality_pub_created_idx'),
        ),
        migrations.AddIndex(
            model_name='streetviewqualityreport',
            index=models.Index(fields=['status'], name='sv_quality_status_idx'),
        ),
        migrations.AddIndex(
            model_name='streetviewhistoryevent',
            index=models.Index(fields=['publication', 'created_at'], name='sv_hist_pub_created_idx'),
        ),
        migrations.AddIndex(
            model_name='streetviewhistoryevent',
            index=models.Index(fields=['action'], name='sv_hist_action_idx'),
        ),
        migrations.AddIndex(
            model_name='streetviewanalyticsevent',
            index=models.Index(fields=['publication', 'created_at'], name='sv_analytics_pub_created_idx'),
        ),
        migrations.AddIndex(
            model_name='streetviewanalyticsevent',
            index=models.Index(fields=['event_type'], name='sv_analytics_type_idx'),
        ),
    ]
