FROM nginx:latest

RUN mkdir -p /etc/nginx/ssl

RUN apt-get update \
    && apt-get install -y --no-install-recommends openssl \
    && rm -rf /var/lib/apt/lists/*

RUN openssl dhparam -out /etc/nginx/dhparam.pem 2048

RUN rm -f /etc/nginx/conf.d/default.conf

COPY ./default.conf /etc/nginx/conf.d/default.conf

COPY ./mjs.types /etc/nginx/conf.d/mjs.types

COPY ./start-nginx.sh /start-nginx.sh

RUN chmod +x /start-nginx.sh

EXPOSE 80
EXPOSE 443

CMD ["/start-nginx.sh"]