FROM nginx:latest

# Crée les dossiers nécessaires
RUN mkdir -p /etc/nginx/ssl

# Installe openssl
RUN apt-get update \
    && apt-get install -y --no-install-recommends openssl \
    && rm -rf /var/lib/apt/lists/*

# Génère le fichier Diffie-Hellman
RUN openssl dhparam -out /etc/nginx/dhparam.pem 2048

# Supprime la configuration Nginx par défaut
RUN rm -f /etc/nginx/conf.d/default.conf

# Copie la configuration principale
COPY ./default.conf /etc/nginx/conf.d/default.conf

# Copie le fichier MIME personnalisé avec prise en charge de .mjs
COPY ./mime.types /etc/nginx/mime.types

# Copie le script de démarrage
COPY ./start-nginx.sh /start-nginx.sh

RUN chmod +x /start-nginx.sh

EXPOSE 80
EXPOSE 443

CMD ["/start-nginx.sh"]