# Generated by Django 5.2.13 on 2026-07-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('store', 'Store'), ('boutique', 'Boutique'), ('supermarket', 'Supermarket'), ('shopping_mall', 'Shopping Mall'), ('showroom', 'Showroom'), ('pharmacy', 'Pharmacy'), ('beauty_salon', 'Beauty Salon'), ('barbershop', 'Barbershop'), ('wedding_hall', 'Wedding Hall'), ('event_hall', 'Event Hall'), ('conference_hall', 'Conference Hall'), ('banquet_hall', 'Banquet Hall'), ('church', 'Church'), ('ceremony_place', 'Ceremony Place'), ('party_venue', 'Party Venue'), ('house', 'House'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('studio', 'Studio'), ('office', 'Office'), ('building', 'Building'), ('land', 'Land'), ('real_estate', 'Real Estate'), ('hotel', 'Hotel'), ('resort', 'Resort'), ('guest_house', 'Guest House'), ('lodge', 'Lodge'), ('beach', 'Beach'), ('tourist_site', 'Tourist Site'), ('museum', 'Museum'), ('park', 'Park'), ('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('bar', 'Bar'), ('lounge', 'Lounge'), ('club', 'Club'), ('fast_food', 'Fast Food'), ('hospital', 'Hospital'), ('clinic', 'Clinic'), ('dental_clinic', 'Dental Clinic'), ('spa', 'Spa'), ('gym', 'Gym'), ('fitness_center', 'Fitness Center'), ('school', 'School'), ('university', 'University'), ('training_center', 'Training Center'), ('library', 'Library'), ('company', 'Company'), ('bank', 'Bank'), ('government_office', 'Government Office'), ('coworking_space', 'Coworking Space'), ('airport', 'Airport'), ('bus_station', 'Bus Station'), ('car_dealership', 'Car Dealership'), ('garage', 'Garage'), ('other', 'Other')], max_length=40),
        ),
    ]
