# Generated by Django 5.2.13 on 2026-07-17 16:54

import apps.vendors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_tracking_notifications_reviews_search_pwa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'ordering': ('country_code', 'province', 'name')},
        ),
        migrations.RenameIndex(
            model_name='customerbehaviorevent',
            new_name='vendors_cus_organiz_bea198_idx',
            old_name='vendors_cus_organiz_6f48a7_idx',
        ),
        migrations.RenameIndex(
            model_name='customernotification',
            new_name='vendors_cus_user_id_a3e363_idx',
            old_name='vendors_cus_user_id_a87ef0_idx',
        ),
        migrations.RenameIndex(
            model_name='productreview',
            new_name='vendors_pro_product_0c8a64_idx',
            old_name='vendors_pro_product_97b7d0_idx',
        ),
        migrations.RenameIndex(
            model_name='stockreservation',
            new_name='vendors_sto_product_65d7d3_idx',
            old_name='vendors_sto_product_7a9ab4_idx',
        ),
        migrations.RenameIndex(
            model_name='stockreservation',
            new_name='vendors_sto_session_48856b_idx',
            old_name='vendors_sto_session_f1ef7c_idx',
        ),
        migrations.RenameIndex(
            model_name='webvitalmeasurement',
            new_name='vendors_web_name_e474b4_idx',
            old_name='vendors_web_name_4fe49f_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.vendors.models.vendor_product_upload_to),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=apps.vendors.models.vendor_product_gallery_upload_to),
        ),
        migrations.AlterField(
            model_name='productreviewimage',
            name='image',
            field=models.ImageField(upload_to=apps.vendors.models.product_review_upload_to),
        ),
    ]
