from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
 initial=True
 dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL),('organizations','0001_initial')]
 operations=[
 migrations.CreateModel(name='DataSourceConnection',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('provider',models.CharField(choices=[('search_console','Google Search Console'),('analytics','Google Analytics 4'),('business_profile','Google Business Profile'),('google_trends','Google Trends'),('bing','Bing Webmaster'),('internal','Twinscopes Internal')],max_length=40)),('name',models.CharField(blank=True,max_length=120)),('credential_ref',models.CharField(blank=True,help_text='Key in settings.GROWTH_AI_CREDENTIALS; secrets are not stored here.',max_length=120)),('config',models.JSONField(blank=True,default=dict)),('is_enabled',models.BooleanField(default=True)),('last_synced_at',models.DateTimeField(blank=True,null=True)),('last_error',models.TextField(blank=True)),('organization',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='growth_connections',to='organizations.organization'))]),
 migrations.CreateModel(name='TrackedKeyword',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('keyword',models.CharField(max_length=255)),('country',models.CharField(default='ZA',max_length=8)),('language',models.CharField(default='en',max_length=12)),('is_active',models.BooleanField(default=True)),('organization',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='tracked_keywords',to='organizations.organization'))]),
 migrations.CreateModel(name='SyncRun',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('status',models.CharField(choices=[('pending','Pending'),('running','Running'),('success','Success'),('failed','Failed'),('partial','Partial')],default='pending',max_length=20)),('started_at',models.DateTimeField(blank=True,null=True)),('finished_at',models.DateTimeField(blank=True,null=True)),('rows_received',models.PositiveIntegerField(default=0)),('rows_saved',models.PositiveIntegerField(default=0)),('cursor',models.CharField(blank=True,max_length=255)),('error',models.TextField(blank=True)),('metadata',models.JSONField(blank=True,default=dict)),('connection',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='sync_runs',to='growth_ai.datasourceconnection'))],options={'ordering':['-created_at']}),
 migrations.CreateModel(name='TrafficMetric',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('metric_date',models.DateField(db_index=True)),('granularity',models.CharField(default='day',max_length=20)),('dimensions',models.JSONField(blank=True,default=dict)),('dimension_hash',models.CharField(db_index=True,max_length=64)),('metrics',models.JSONField(blank=True,default=dict)),('connection',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='metrics',to='growth_ai.datasourceconnection')),('organization',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='growth_metrics',to='organizations.organization'))]),
 migrations.CreateModel(name='InternalDailySnapshot',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('snapshot_date',models.DateField(db_index=True)),('metrics',models.JSONField(blank=True,default=dict)),('organization',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name='growth_daily_snapshots',to='organizations.organization'))],options={'ordering':['-snapshot_date']}),
 migrations.CreateModel(name='GrowthEvent',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('event_name',models.CharField(db_index=True,max_length=80)),('session_key',models.CharField(blank=True,db_index=True,max_length=64)),('tour_id',models.PositiveBigIntegerField(blank=True,db_index=True,null=True)),('product_id',models.PositiveBigIntegerField(blank=True,db_index=True,null=True)),('page_path',models.CharField(blank=True,max_length=500)),('referrer',models.CharField(blank=True,max_length=500)),('device',models.CharField(blank=True,max_length=30)),('source',models.CharField(blank=True,max_length=120)),('metadata',models.JSONField(blank=True,default=dict)),('occurred_at',models.DateTimeField(db_index=True)),('organization',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='growth_events',to='organizations.organization')),('user',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='growth_events',to=settings.AUTH_USER_MODEL))]),
 migrations.AddConstraint(model_name='datasourceconnection',constraint=models.UniqueConstraint(fields=('organization','provider','name'),name='growth_unique_source')),migrations.AddConstraint(model_name='trackedkeyword',constraint=models.UniqueConstraint(fields=('organization','keyword','country','language'),name='growth_unique_keyword')),migrations.AddConstraint(model_name='trafficmetric',constraint=models.UniqueConstraint(fields=('connection','metric_date','granularity','dimension_hash'),name='growth_unique_metric_row')),migrations.AddConstraint(model_name='internaldailysnapshot',constraint=models.UniqueConstraint(fields=('organization','snapshot_date'),name='growth_unique_internal_snapshot'))]
