# Generated by Django 5.2.13 on 2026-07-17 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth_ai', '0001_initial'),
        ('organizations', '0003_organization_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datasourceconnection',
            index=models.Index(fields=['provider', 'is_enabled'], name='growth_ai_d_provide_b4c417_idx'),
        ),
        migrations.AddIndex(
            model_name='datasourceconnection',
            index=models.Index(fields=['organization', 'provider'], name='growth_ai_d_organiz_080704_idx'),
        ),
        migrations.AddIndex(
            model_name='growthevent',
            index=models.Index(fields=['organization', 'occurred_at'], name='growth_ai_g_organiz_5a97a4_idx'),
        ),
        migrations.AddIndex(
            model_name='growthevent',
            index=models.Index(fields=['event_name', 'occurred_at'], name='growth_ai_g_event_n_6eefb8_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficmetric',
            index=models.Index(fields=['organization', 'metric_date'], name='growth_ai_t_organiz_a61676_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficmetric',
            index=models.Index(fields=['connection', 'metric_date'], name='growth_ai_t_connect_2aabb0_idx'),
        ),
    ]
