# Generated by Django 5.2.13 on 2026-04-16 16:27

import apps.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.organizations.models.organization_logo_upload_to),
        ),
    ]
