import decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0004_organization_enterprise_profile"),
        ("places", "0002_alter_place_category"),
        ("tours", "0011_repair_legacy_ai_analysis_statuses"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationIntelligenceProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("domain_kind", models.CharField(choices=[("general", "General"), ("healthcare", "Healthcare"), ("real_estate", "Real estate"), ("hospitality", "Hospitality"), ("mixed", "Mixed")], db_index=True, default="general", max_length=24)),
                ("default_locale", models.CharField(default="en", max_length=16)),
                ("timezone", models.CharField(default="Africa/Johannesburg", max_length=80)),
                ("country_code", models.CharField(blank=True, max_length=3)),
                ("auto_sync_website", models.BooleanField(default=True)),
                ("website_sync_max_pages", models.PositiveSmallIntegerField(default=30)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_status", models.CharField(blank=True, max_length=24)),
                ("last_sync_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="intelligence_profile", to="organizations.organization")),
            ],
        ),
        migrations.CreateModel(
            name="HealthcareFacilityProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("appointment_phone", models.CharField(blank=True, max_length=60)),
                ("appointment_email", models.EmailField(blank=True, max_length=254)),
                ("appointment_url", models.URLField(blank=True)),
                ("emergency_phone", models.CharField(blank=True, max_length=60)),
                ("accepts_walk_ins", models.BooleanField(default=False)),
                ("telemedicine_available", models.BooleanField(default=False)),
                ("opening_hours", models.JSONField(blank=True, default=list)),
                ("specialties", models.JSONField(blank=True, default=list)),
                ("insurance_providers", models.JSONField(blank=True, default=list)),
                ("accessibility", models.JSONField(blank=True, default=list)),
                ("source_url", models.URLField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("place", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="healthcare_profile", to="places.place")),
            ],
        ),
        migrations.CreateModel(
            name="HospitalityProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("star_rating", models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ("room_count", models.PositiveIntegerField(blank=True, null=True)),
                ("price_from", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("booking_url", models.URLField(blank=True)),
                ("is_available", models.BooleanField(default=True)),
                ("source_url", models.URLField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("place", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="hospitality_profile", to="places.place")),
            ],
        ),
        migrations.CreateModel(
            name="MedicalSpecialty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("default_duration_minutes", models.PositiveSmallIntegerField(default=30)),
                ("source_url", models.URLField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="medical_specialties", to="organizations.organization")),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="MedicalPractitioner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("professional_title", models.CharField(blank=True, max_length=180)),
                ("bio", models.TextField(blank=True)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("public_phone", models.CharField(blank=True, max_length=60)),
                ("public_email", models.EmailField(blank=True, max_length=254)),
                ("booking_url", models.URLField(blank=True)),
                ("booking_mode", models.CharField(choices=[("request", "Request confirmation"), ("direct", "Direct booking"), ("contact", "Contact facility")], default="request", max_length=16)),
                ("show_public_phone", models.BooleanField(default=False)),
                ("show_public_email", models.BooleanField(default=False)),
                ("source_url", models.URLField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="medical_practitioners", to="organizations.organization")),
                ("place", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="medical_practitioners", to="places.place")),
                ("specialty", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="practitioners", to="domain_intelligence.medicalspecialty")),
            ],
            options={"ordering": ("full_name",)},
        ),
        migrations.CreateModel(
            name="PractitionerAvailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("weekday", models.PositiveSmallIntegerField(choices=[(0, "Monday"), (1, "Tuesday"), (2, "Wednesday"), (3, "Thursday"), (4, "Friday"), (5, "Saturday"), (6, "Sunday")])),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                ("location_label", models.CharField(blank=True, max_length=180)),
                ("appointment_mode", models.CharField(default="in_person", max_length=24)),
                ("is_active", models.BooleanField(default=True)),
                ("practitioner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="availability_slots", to="domain_intelligence.medicalpractitioner")),
            ],
            options={"ordering": ("weekday", "starts_at")},
        ),
        migrations.CreateModel(
            name="PropertyListingProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("listing_type", models.CharField(choices=[("rent", "For rent"), ("sale", "For sale"), ("short_stay", "Short stay")], db_index=True, default="rent", max_length=20)),
                ("property_type", models.CharField(choices=[("house", "House"), ("apartment", "Apartment"), ("villa", "Villa"), ("studio", "Studio"), ("office", "Office"), ("building", "Building"), ("land", "Land"), ("other", "Other")], db_index=True, default="house", max_length=20)),
                ("bedrooms", models.PositiveSmallIntegerField(db_index=True, default=0)),
                ("bathrooms", models.DecimalField(decimal_places=1, default=decimal.Decimal("0.0"), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ("parking_spaces", models.PositiveSmallIntegerField(default=0)),
                ("furnished", models.BooleanField(default=False)),
                ("area_sqm", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("price", models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=14, null=True)),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("available_from", models.DateField(blank=True, null=True)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("pet_friendly", models.BooleanField(default=False)),
                ("availability_status", models.CharField(choices=[("available", "Available"), ("reserved", "Reserved"), ("rented", "Rented"), ("sold", "Sold"), ("unavailable", "Unavailable")], db_index=True, default="available", max_length=20)),
                ("source_url", models.URLField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("place", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="property_profile", to="places.place")),
            ],
        ),
        migrations.CreateModel(
            name="VerifiedSourceFact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(db_index=True, max_length=80)),
                ("entity_key", models.CharField(blank=True, db_index=True, max_length=255)),
                ("field_name", models.CharField(db_index=True, max_length=120)),
                ("value", models.JSONField(blank=True, default=dict)),
                ("source_url", models.URLField()),
                ("confidence", models.DecimalField(decimal_places=3, default=decimal.Decimal("1.000"), max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ("verified_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="verified_domain_facts", to="organizations.organization")),
                ("place", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="verified_domain_facts", to="places.place")),
            ],
            options={"ordering": ("-verified_at",)},
        ),
        migrations.CreateModel(
            name="DiscoverySearchLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.CharField(max_length=500)),
                ("normalized_intent", models.JSONField(blank=True, default=dict)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("session_key", models.CharField(blank=True, db_index=True, max_length=80)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("selected_tour", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="discovery_search_selections", to="tours.tour")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddConstraint(
            model_name="medicalspecialty",
            constraint=models.UniqueConstraint(fields=("organization", "slug"), name="unique_medical_specialty_slug_per_org"),
        ),
        migrations.AddIndex(
            model_name="medicalpractitioner",
            index=models.Index(fields=["organization", "is_active"], name="domain_inte_organiz_81eeb1_idx"),
        ),
        migrations.AddIndex(
            model_name="medicalpractitioner",
            index=models.Index(fields=["organization", "specialty"], name="domain_inte_organiz_410a24_idx"),
        ),
        migrations.AddConstraint(
            model_name="medicalpractitioner",
            constraint=models.UniqueConstraint(fields=("organization", "full_name", "specialty"), name="unique_practitioner_name_specialty_per_org"),
        ),
        migrations.AddIndex(
            model_name="propertylistingprofile",
            index=models.Index(fields=["listing_type", "property_type", "bedrooms"], name="domain_inte_listing_bf9aec_idx"),
        ),
        migrations.AddIndex(
            model_name="propertylistingprofile",
            index=models.Index(fields=["availability_status", "price"], name="domain_inte_availab_fa1930_idx"),
        ),
        migrations.AddIndex(
            model_name="verifiedsourcefact",
            index=models.Index(fields=["organization", "entity_type", "field_name"], name="domain_inte_organiz_e96250_idx"),
        ),
        migrations.AddConstraint(
            model_name="verifiedsourcefact",
            constraint=models.UniqueConstraint(fields=("organization", "entity_type", "entity_key", "field_name", "source_url"), name="unique_verified_domain_fact_source"),
        ),
    ]
