# Generated by Twinscopes intelligence operations patch.
import uuid
from decimal import Decimal

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("domain_intelligence", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationintelligenceprofile",
            name="next_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationintelligenceprofile",
            name="readiness_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="organizationintelligenceprofile",
            name="readiness_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationintelligenceprofile",
            name="readiness_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="organizationintelligenceprofile",
            name="readiness_status",
            field=models.CharField(choices=[("not_ready", "Not ready"), ("in_progress", "In progress"), ("review", "Needs review"), ("ready", "Client ready")], db_index=True, default="not_ready", max_length=24),
        ),
        migrations.CreateModel(
            name="OrganizationIntelligenceRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("trigger", models.CharField(choices=[("manual", "Manual"), ("scheduled", "Scheduled"), ("onboarding", "Onboarding"), ("api", "API")], default="manual", max_length=24)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("succeeded", "Succeeded"), ("partial", "Partial"), ("failed", "Failed"), ("cancelled", "Cancelled")], db_index=True, default="queued", max_length=24)),
                ("task_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("website_url", models.URLField(blank=True)),
                ("max_pages", models.PositiveSmallIntegerField(default=25)),
                ("pages_crawled", models.PositiveIntegerField(default=0)),
                ("documents_indexed", models.PositiveIntegerField(default=0)),
                ("chunks_indexed", models.PositiveIntegerField(default=0)),
                ("services_collected", models.PositiveIntegerField(default=0)),
                ("facts_collected", models.PositiveIntegerField(default=0)),
                ("review_items_created", models.PositiveIntegerField(default=0)),
                ("practitioners_collected", models.PositiveIntegerField(default=0)),
                ("specialties_collected", models.PositiveIntegerField(default=0)),
                ("social_links_collected", models.PositiveIntegerField(default=0)),
                ("readiness_before", models.PositiveSmallIntegerField(default=0)),
                ("readiness_after", models.PositiveSmallIntegerField(default=0)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="intelligence_runs", to="organizations.organization")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requested_intelligence_runs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="IntelligenceReviewItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("item_type", models.CharField(choices=[("profile", "Organization profile"), ("contact", "Public contact"), ("social", "Social media"), ("location", "Location"), ("service", "Service offering"), ("healthcare", "Healthcare information"), ("property", "Property information"), ("hospitality", "Hospitality information"), ("other", "Other")], db_index=True, default="other", max_length=24)),
                ("target_model", models.CharField(max_length=80)),
                ("target_field", models.CharField(blank=True, max_length=120)),
                ("entity_key", models.CharField(blank=True, max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("current_value", models.JSONField(blank=True, default=dict)),
                ("proposed_value", models.JSONField(blank=True, default=dict)),
                ("source_url", models.URLField()),
                ("confidence", models.DecimalField(decimal_places=3, default=Decimal("0.750"), max_digits=4, validators=[MinValueValidator(0), MaxValueValidator(1)])),
                ("reason", models.TextField(blank=True)),
                ("is_public_safe", models.BooleanField(default=True)),
                ("status", models.CharField(choices=[("pending", "Pending review"), ("applied", "Applied"), ("rejected", "Rejected")], db_index=True, default="pending", max_length=24)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="intelligence_review_items", to="organizations.organization")),
                ("place", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="intelligence_review_items", to="places.place")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_intelligence_items", to=settings.AUTH_USER_MODEL)),
                ("run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="review_items", to="domain_intelligence.organizationintelligencerun")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddIndex(model_name="organizationintelligencerun", index=models.Index(fields=["organization", "status"], name="domain_inte_organiz_745294_idx")),
        migrations.AddIndex(model_name="organizationintelligencerun", index=models.Index(fields=["status", "created_at"], name="domain_inte_status_a61cf2_idx")),
        migrations.AddIndex(model_name="intelligencereviewitem", index=models.Index(fields=["organization", "status"], name="domain_inte_organiz_7a3a0e_idx")),
        migrations.AddIndex(model_name="intelligencereviewitem", index=models.Index(fields=["target_model", "target_field"], name="domain_inte_target__0e0f10_idx")),
    ]
